import 'dart:io';
import 'dart:convert';
void main() {
  var f = File('lib/l10n/app_sv.arb'); var d = json.decode(f.readAsStringSync()) as Map<String,dynamic>;
  d['step']='Steg'; d['skip']='Hoppa over'; d['back']='Tillbaka'; d['next']='Nasta';
  d['createProfile']='Skapa profil'; d['basicInfo']='Grundinfo'; d['firstName']='Fornamn'; d['yourFirstName']='Ditt fornamn'; d['birthDate']='Fodelsedatum'; d['years']='ar';
  d['male']='Man'; d['female']='Kvinna'; d['ezidiIdentity']='Ezidisk identitet'; d['tribe']='Stam / Ashiret'; d['iAmLookingFor']='Jag soker';
  d['marriage']='Aktenskap'; d['dating']='Dejting'; d['friendship']='Vanskap';
  d['aboutYou']='Om dig'; d['location']='Stad'; d['jobTitle']='Yrke'; d['educationLevel']='Utbildning';
  d['single']='Singel'; d['divorced']='Skild'; d['widowed']='Ankling';
  d['noChildren']='Inga barn'; d['hasChildren']='Har barn'; d['wantsChildren']='Vill ha barn'; d['maybeChildren']='Kanske';
  d['interestsHobbies']='Intressen och hobbyer'; d['characterTraits']='Karaktar och egenskaper';
  d['aboutMe']='Om mig'; d['threeThings']='Tre viktiga saker for mig'; d['profileCreated']='Profil skapad!';
  f.writeAsStringSync(JsonEncoder.withIndent('  ').convert(d)); print('SV done');
  f = File('lib/l10n/app_fa.arb'); d = json.decode(f.readAsStringSync()) as Map<String,dynamic>;
  d['step']='Gam'; d['skip']='Rad shodan'; d['back']='Bazgasht'; d['next']='Baadi';
  d['createProfile']='Sakht-e profil'; d['basicInfo']='Etelaat-e payeh'; d['firstName']='Nam'; d['yourFirstName']='Nam-e shoma'; d['birthDate']='Tarikh-e tavalod'; d['years']='sal';
  d['male']='Mard'; d['female']='Zan'; d['ezidiIdentity']='Hoviat-e Izadi'; d['tribe']='Tayefe / Ashiret'; d['iAmLookingFor']='Man donbal-e';
  d['marriage']='Ezdevaj'; d['dating']='Ashnaee'; d['friendship']='Dusti';
  d['aboutYou']='Darbare-ye shoma'; d['location']='Shahr'; d['jobTitle']='Shogl'; d['educationLevel']='Tahsilat';
  d['single']='Mojarrad'; d['divorced']='Motaleqe'; d['widowed']='Bive';
  d['noChildren']='Bedun-e farzand'; d['hasChildren']='Farzand darad'; d['wantsChildren']='Mikhahad farzand'; d['maybeChildren']='Shayad';
  d['interestsHobbies']='Alaqemandi va sargarmie'; d['characterTraits']='Shakhsiat va vizhegiha';
  d['aboutMe']='Darbare-ye man'; d['threeThings']='Se chiz-e mohem baraye man'; d['profileCreated']='Profil sakhte shod!';
  f.writeAsStringSync(JsonEncoder.withIndent('  ').convert(d)); print('FA done');
  f = File('lib/l10n/app_hy.arb'); d = json.decode(f.readAsStringSync()) as Map<String,dynamic>;
  d['step']='Qayl'; d['skip']='Bac tal'; d['back']='Het'; d['next']='Hajord';
  d['createProfile']='Stexcel profil'; d['basicInfo']='Himnayin tvekyalner'; d['firstName']='Anun'; d['yourFirstName']='Dzer anun'; d['birthDate']='Cnndyan amsakit'; d['years']='tariq';
  d['male']='Arakan'; d['female']='Kin'; d['ezidiIdentity']='Ezidi inqnutyun'; d['tribe']='Tsex / Ashiret'; d['iAmLookingFor']='Yes ponum em';
  d['marriage']='Amousnutyun'; d['dating']='Zharankavorum'; d['friendship']='Ynkerutyun';
  d['aboutYou']='Dzer masin'; d['location']='Qaghaq'; d['jobTitle']='Masnagitutyun'; d['educationLevel']='Krthutyun';
  d['single']='Amuri'; d['divorced']='Azatagrvats'; d['widowed']='Ayri';
  d['noChildren']='Erekaner chkan'; d['hasChildren']='Erekaner ka'; d['wantsChildren']='Erekaner e uzum'; d['maybeChildren']='Gucee';
  d['interestsHobbies']='Hetaqrqutyunner ev hobbiner'; d['characterTraits']='Bnutagir ev vorakner';
  d['aboutMe']='Im masin'; d['threeThings']='Erek karevore baners'; d['profileCreated']='Profil stexcvec!';
  f.writeAsStringSync(JsonEncoder.withIndent('  ').convert(d)); print('HY done');
  f = File('lib/l10n/app_ka.arb'); d = json.decode(f.readAsStringSync()) as Map<String,dynamic>;
  d['step']='Nabiji'; d['skip']='Gamotoveba'; d['back']='Ukhan'; d['next']='Shemdegi';
  d['createProfile']='Profilis sheqmna'; d['basicInfo']='Dziritadi info'; d['firstName']='Sakheli'; d['yourFirstName']='Tkveni sakheli'; d['birthDate']='Dabadebis tarighi'; d['years']='tseli';
  d['male']='Mamakaci'; d['female']='Qali'; d['ezidiIdentity']='Eziduri identoba'; d['tribe']='Tomi / Ashiret'; d['iAmLookingFor']='Me vedzeb';
  d['marriage']='Qorcineba'; d['dating']='Paemnebi'; d['friendship']='Megobroba';
  d['aboutYou']='Tkvens shesakheb'; d['location']='Qalaqi'; d['jobTitle']='Profesia'; d['educationLevel']='Ganatleba';
  d['single']='Martokhi'; d['divorced']='Gancalkevebuli'; d['widowed']='Qvriva';
  d['noChildren']='Shvilebi ar aqvs'; d['hasChildren']='Shvilebi aqvs'; d['wantsChildren']='Shvilebis survili'; d['maybeChildren']='Shesadzloa';
  d['interestsHobbies']='Interesebi da hobiebi'; d['characterTraits']='Khasiati da tvisebebi';
  d['aboutMe']='Chems shesakheb'; d['threeThings']='Sami mnisvnelovani ram'; d['profileCreated']='Profili sheiqmna!';
  f.writeAsStringSync(JsonEncoder.withIndent('  ').convert(d)); print('KA done');
}